[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
