[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
AliasTables = "66dad0bd-aa9a-41b7-9441-69ab47430ed8"
ArgTools = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
AxisAlgorithms = "13072b0f-2c55-5437-9ae7-d433b7a33950"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
BitFlags = "d1d4a3ce-64b1-5f1a-9ba4-7e7e69966f35"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
Cairo_jll = "83423d85-b0ee-5818-9007-b63ccbeb887a"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
ConcurrentUtilities = "f0e56b4a-5159-44fe-b623-3e5288b988bb"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DataValueInterfaces = "e2d170a0-9d28-54be-80f0-106bbe20a464"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
EarCut_jll = "5ae413db-bbd1-5e63-b57d-d24a61df00f5"
EpollShim_jll = "2702e6a9-849d-5ed8-8c21-79e8b8f9ee43"
ExceptionUnwrapping = "460bff9d-24e4-43bc-9d9f-a8973cb893f4"
Expat_jll = "2e619515-83b5-522b-bb60-26c02a35a201"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
FFMPEG_jll = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Fontconfig_jll = "a3f928ae-7b40-5064-980b-68af3947d34b"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
FreeType2_jll = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
FriBidi_jll = "559328eb-81f9-559d-9380-de523a88c83c"
GLFW_jll = "0656b61e-2033-5cc2-a64a-77c0f6c09b89"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
GR_jll = "d2c73de3-f751-5644-a686-071e5b155ba9"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Gettext_jll = "78b55507-aeef-58d4-861c-77aaff3498b1"
Glib_jll = "7746bdde-850d-59dc-9ae8-88ece973131d"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphite2_jll = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Grisu = "42e2da0e-8278-4e71-bc24-59509adca0fe"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
HarfBuzz_jll = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IrrationalConstants = "92d709cd-6900-40b7-9082-c6be49f344b6"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
JLFzf = "1019f520-868f-41f5-a6de-eb00f4b6a39c"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JpegTurbo_jll = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
LAME_jll = "c1c5ebd0-6772-5130-a774-d5fcae4a789d"
LERC_jll = "88015f11-f218-50d7-93a8-a6af411a945d"
LLVMOpenMP_jll = "1d63c593-3942-5779-bab2-d838dc0a180e"
LZO_jll = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LibCURL = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
LibCURL_jll = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
LibSSH2_jll = "29816b5a-b9ab-546f-933c-edad1886dfa8"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Libffi_jll = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
Libgcrypt_jll = "d4300ac3-e22c-5743-9152-c294e39db1e4"
Libglvnd_jll = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29"
Libgpg_error_jll = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8"
Libiconv_jll = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
Libmount_jll = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
Libtiff_jll = "89763e89-9b03-5906-acba-b20f662cd828"
Libuuid_jll = "38a345b3-de98-5d2b-a5d3-14cd9215e700"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
MbedTLS_jll = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
MozillaCACerts_jll = "14a3606d-f60d-562e-9121-12d972cd8159"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
NetworkOptions = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Ogg_jll = "e7412a2a-1a6e-54c0-be00-318e2571c051"
OpenBLAS_jll = "4536629a-c528-5b80-bd46-f80d51c5b363"
OpenLibm_jll = "05823500-19ac-5b8b-9628-191a04bc5112"
OpenSSL = "4d8831e6-92b7-49fb-bdf8-b643e874388c"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
OpenSpecFun_jll = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
Opus_jll = "91d4177d-7536-5919-b921-800302f37372"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PCRE2_jll = "efcefdf7-47ab-520b-bdef-62a2eaa19f15"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
Pixman_jll = "30392449-352a-5448-841d-b1acce4e97dc"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PtrArrays = "43287f4e-b6f4-7ad1-bb20-aadabca52c3d"
Qt6Base_jll = "c0090381-4147-56d7-9ebc-da0b1113ec56"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Ratios = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecipesPipeline = "01d81517-befc-4cb6-b9ec-a95719d0359c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Rmath = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
Rmath_jll = "f50d1b31-88e8-58de-be2c-1cc44531875f"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
Showoff = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
SimpleBufferStream = "777ac1f9-54b0-4bf8-805c-2214025038e7"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
SoftGlobalScope = "b85f4697-e234-5449-a836-ec8e2f98b302"
SortingAlgorithms = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
SuiteSparse_jll = "bea87d4a-7f5b-5778-9afe-8cc45184846c"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
TensorCore = "62fd8b95-f654-4bbd-a8a5-9c27f68ccd50"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
UnicodeFun = "1cfade01-22cf-5700-b092-accc4b62d6e1"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulLatexify = "45397f5d-5981-4c77-b2b3-fc36d6e9b728"
Unzip = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"
VersionParsing = "81def892-9a0e-5fdd-b105-ffc91e053289"
Vulkan_Loader_jll = "a44049a8-05dd-5a78-86c9-5fde0876e88c"
Wayland_jll = "a2964d1f-97da-50d4-b82a-358c7fce9d89"
Wayland_protocols_jll = "2381bf8a-dfd0-557d-9999-79630e7b1b91"
WoodburyMatrices = "efce3f68-66dc-5838-9240-27a6d6f5f9b6"
XML2_jll = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
XSLT_jll = "aed1982a-8fda-507f-9586-7b0439959a61"
XZ_jll = "ffd25f8a-64ca-5728-b0f7-c24cf3aae800"
Xorg_libICE_jll = "f67eecfb-183a-506d-b269-f58e52b52d7c"
Xorg_libSM_jll = "c834827a-8449-5923-a945-d239c165b7dd"
Xorg_libX11_jll = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
Xorg_libXau_jll = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
Xorg_libXcursor_jll = "935fb764-8cf2-53bf-bb30-45bb1f8bf724"
Xorg_libXdmcp_jll = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
Xorg_libXext_jll = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
Xorg_libXfixes_jll = "d091e8ba-531a-589c-9de9-94069b037ed8"
Xorg_libXi_jll = "a51aa0fd-4e3c-5386-b890-e753decda492"
Xorg_libXinerama_jll = "d1454406-59df-5ea1-beac-c340f2130bc3"
Xorg_libXrandr_jll = "ec84b674-ba8e-5d96-8ba1-2a689ba10484"
Xorg_libXrender_jll = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
Xorg_libpthread_stubs_jll = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
Xorg_libxcb_jll = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
Xorg_libxkbfile_jll = "cc61e674-0454-545c-8b26-ed2c68acab7a"
Xorg_xcb_util_cursor_jll = "e920d4aa-a673-5f3a-b3d7-f755a4d47c43"
Xorg_xcb_util_image_jll = "12413925-8142-5f55-bb0e-6d7ca50bb09b"
Xorg_xcb_util_jll = "2def613f-5ad1-5310-b15b-b15d46f528f5"
Xorg_xcb_util_keysyms_jll = "975044d2-76e6-5fbe-bf08-97ce7c6574c7"
Xorg_xcb_util_renderutil_jll = "0d47668e-0667-5a69-a72c-f761630bfb7e"
Xorg_xcb_util_wm_jll = "c22f9ab0-d5fe-5066-847c-f4bb1cd4e361"
Xorg_xkbcomp_jll = "35661453-b289-5fab-8a00-3d9160c6a3a4"
Xorg_xkeyboard_config_jll = "33bec58e-1273-512f-9401-5d533626f822"
Xorg_xtrans_jll = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
ZeroMQ_jll = "8f1865be-045e-5c20-9c9f-bfbfb0764568"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Zstd_jll = "3161d3a3-bdf6-5164-811a-617609db77b4"
eudev_jll = "35ca27e7-8b34-5b7f-bca9-bdc33f59eb06"
fzf_jll = "214eeab7-80f7-51ab-84ad-2988db7cef09"
gperf_jll = "1a1c6b14-54f6-533d-8383-74cd7377aa70"
libaom_jll = "a4ae2306-e953-59d6-aa16-d00cac43593b"
libass_jll = "0ac62f75-1d6f-5e53-bd7c-93b484bb37c0"
libblastrampoline_jll = "8e850b90-86db-534c-a0d3-1478176c7d93"
libevdev_jll = "2db6ffa8-e38f-5e21-84af-90c45d0032cc"
libfdk_aac_jll = "f638f0a6-7fb0-5443-88ba-1cc74229b280"
libinput_jll = "36db933b-70db-51c0-b978-0f229ee0e533"
libpng_jll = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
libsodium_jll = "a9144af2-ca23-56d9-984f-0d03f7b5ccf8"
libvorbis_jll = "f27f6e37-5d2b-51aa-960f-b287f2bc3b7a"
mtdev_jll = "009596ad-96f7-51b1-9f1b-5ce2d5e8a71e"
nghttp2_jll = "8e850ede-7688-5339-a07c-302acd2aaf8d"
p7zip_jll = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"
x264_jll = "1270edf5-f2f9-52d2-97e9-ab00b5d0237a"
x265_jll = "dfaa095f-4041-5dcd-9319-2fabd8486b76"
xkbcommon_jll = "d8fb68d0-12a3-5cfd-a85a-d49703b185fd"
